### ISSUE TITLE
Signs do not work

### ISSUE THREAD

**Issue by KingHorse2015** [Pocketkid2/Survival-Games#10]
`Plugins;'Plugins (14): WorldEdit, OpToggle, iConomy, PermissionsEx, SurvivalGames, ViaVersion, Vault, WorldGuard, Multiverse-Core, Essentials, PerWorldInventory, Multiverse-Portals, Quake, EssentialsSpawn
`
Version 1.8.8 `This server is running CraftBukkit version git-Spigot-db6de12-18fbb24 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
[19:54:17 INFO]: Checking version, please wait...
[19:54:18 INFO]: You are 384 version(s) behind
`

`[19:42:23 INFO]: KingHorse issued server command: /sg addwall 1
[19:42:24 WARN]: [SurvivalGames] Task #536 for SurvivalGames v0.5.9 generated an exception
java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
	at java.util.ArrayList.rangeCheck(ArrayList.java:653) ~[?:1.8.0_101]
	at java.util.ArrayList.get(ArrayList.java:429) ~[?:1.8.0_101]
	at org.mcsg.survivalgames.LobbyWall.update(LobbyWall.java:84) ~[?:?]
	at org.mcsg.survivalgames.LobbyWall$1.run(LobbyWall.java:76) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[craftbukkit.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [craftbukkit.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [craftbukkit.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [craftbukkit.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [craftbukkit.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [craftbukkit.jar:git-Spigot-db6de12-18fbb24]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
`

**Comment by KingHorse2015** [comment]
After a reload/restart, it seems to work.

**Comment by Pocketkid2** [comment]
I'll look into it anyway
